apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
spec:
  generators:
  - git:
      repoURL: https://github.com/edin-mahmutovic/argo-playground.git
      revision: HEAD
      directories:
      #- path: cluster-addons/istio-system/*
      #- path: cluster-addons/logging/*
      - path: cluster-addons/metrics/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
      source:
        repoURL: https://github.com/edin-mahmutovic/argo-playground.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'