apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentbit
  labels:
    app: fluentbit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fluentbit
  template:
    metadata:
      labels:
        app: fluentbit
    spec:
      containers:
      - name: fluentbit
        image: nginx:1.14.2
        ports:
        - containerPort: 80