apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-community-alertmanager-config
  namespace: metrics
# https://prometheus.io/docs/alerting/latest/configuration/#configuration-file
data:
  alertmanager.yml: |
    global: {}
    receivers:
    - name: default-receiver
    route:
      group_interval: 30s
      group_wait: 1m
      receiver: default-receiver
      repeat_interval: 30m
