dependencies:
  - name: nri-bundle
    version: ">=2.1.2 <3.0.0"
    repository: https://helm-charts.newrelic.com
  - name: kube-state-metrics
    version: ">=3.0.0 <4.0.0"
    repository: https://prometheus-community.github.io/helm-charts
